-- Seed KTV brands and venues for hosted Supabase.
insert into public.ktv_brands (id, name, booking_url, logo_url, enabled) values
  ('cashbox', '錢櫃', 'https://www.cashboxparty.com/', '🎤', true),
  ('holiday', '好樂迪', 'https://www.holiday.com.tw/', '🎵', true),
  ('star', '星聚點', 'https://www.star-ktv.com/', '⭐', true)
on conflict (id) do update set
  name = excluded.name,
  booking_url = excluded.booking_url,
  logo_url = excluded.logo_url,
  enabled = excluded.enabled;

insert into public.ktv_venues (id, brand_id, name, city, district, address, enabled) values
  ('cashbox-台北市-敦南店', 'cashbox', '敦南店', '台北市', '大安區', '台北市大安區敦化南路一段205號', true),
  ('cashbox-台北市-忠孝店', 'cashbox', '忠孝店', '台北市', '大安區', '台北市大安區忠孝東路四段22號', true),
  ('cashbox-台北市-松江店', 'cashbox', '松江店', '台北市', '中山區', '台北市中山區松江路193號', true),
  ('cashbox-台北市-南京店', 'cashbox', '南京店', '台北市', '中山區', '台北市中山區南京東路二段3號', true),
  ('cashbox-台北市-林森店', 'cashbox', '林森店', '台北市', '中山區', '台北市中山區林森北路312號', true),
  ('cashbox-台北市-中華新館', 'cashbox', '中華新館', '台北市', '中正區', '台北市中正區中華路一段55號', true),
  ('cashbox-新北市-板橋店', 'cashbox', '板橋店', '新北市', '板橋區', '新北市板橋區館前西路', true),
  ('cashbox-新北市-永和店', 'cashbox', '永和店', '新北市', '永和區', '新北市永和區永和路一段129號', true),
  ('cashbox-桃園市-桃園店', 'cashbox', '桃園店', '桃園市', '桃園區', '桃園市桃園區中華路3號', true),
  ('cashbox-桃園市-南崁店', 'cashbox', '南崁店', '桃園市', '蘆竹區', '桃園市蘆竹區南崁路一段290號', true),
  ('cashbox-桃園市-中壢店', 'cashbox', '中壢店', '桃園市', '中壢區', '桃園市中壢區中央東路88號', true),
  ('cashbox-新竹市-新竹店', 'cashbox', '新竹店', '新竹市', '北區', '新竹市北區北大路', true),
  ('cashbox-台中市-台中店', 'cashbox', '台中店', '台中市', '中區', '台中市中區自由路二段32號', true),
  ('cashbox-嘉義市-嘉義店', 'cashbox', '嘉義店', '嘉義市', '西區', '嘉義市西區仁愛路', true),
  ('cashbox-台南市-台南店', 'cashbox', '台南店', '台南市', '中西區', '台南市中西區西門路', true),
  ('cashbox-高雄市-中華新館', 'cashbox', '中華新館', '高雄市', '前金區', '高雄市前金區中華三路', true),
  ('cashbox-高雄市-建興店', 'cashbox', '建興店', '高雄市', '三民區', '高雄市三民區建興路', true),
  ('cashbox-屏東縣-墾丁壹號店', 'cashbox', '墾丁壹號店', '屏東縣', '恆春鎮', '屏東縣恆春鎮墾丁路', true),
  ('holiday-台北市-內湖店', 'holiday', '內湖店', '台北市', '內湖區', '台北市內湖區成功路四段68號', true),
  ('holiday-台北市-石牌店', 'holiday', '石牌店', '台北市', '北投區', '台北市北投區裕民六路120號', true),
  ('holiday-台北市-錦州店', 'holiday', '錦州店', '台北市', '中山區', '台北市中山區錦州街15號', true),
  ('holiday-台北市-中興店', 'holiday', '中興店', '台北市', '松山區', '台北市松山區復興南路一段27號', true),
  ('holiday-台北市-西寧店', 'holiday', '西寧店', '台北市', '萬華區', '台北市萬華區西寧南路62號', true),
  ('holiday-台北市-館前店', 'holiday', '館前店', '台北市', '中正區', '台北市中正區館前路34號', true),
  ('holiday-台北市-通化店', 'holiday', '通化店', '台北市', '信義區', '台北市信義區基隆路二段109號', true),
  ('holiday-台北市-景美店', 'holiday', '景美店', '台北市', '文山區', '台北市文山區羅斯福路六段403號', true),
  ('holiday-基隆市-基隆店', 'holiday', '基隆店', '基隆市', '信義區', '基隆市信義區信一路147號', true),
  ('holiday-新北市-淡水店', 'holiday', '淡水店', '新北市', '淡水區', '新北市淡水區中正路250號', true),
  ('holiday-新北市-汐止店', 'holiday', '汐止店', '新北市', '汐止區', '新北市汐止區中興路158之1號', true),
  ('holiday-新北市-蘆洲店', 'holiday', '蘆洲店', '新北市', '蘆洲區', '新北市蘆洲區長榮路238號', true),
  ('holiday-新北市-重陽店', 'holiday', '重陽店', '新北市', '三重區', '新北市三重區重陽路一段1號', true),
  ('holiday-新北市-三重店', 'holiday', '三重店', '新北市', '三重區', '新北市三重區正義北路68號', true),
  ('holiday-新北市-板前店', 'holiday', '板前店', '新北市', '板橋區', '新北市板橋區南雅南路一段8號', true),
  ('holiday-新北市-板後店', 'holiday', '板後店', '新北市', '板橋區', '新北市板橋區館前東路106號', true),
  ('holiday-新北市-埔墘店', 'holiday', '埔墘店', '新北市', '板橋區', '新北市板橋區三民路一段183號', true),
  ('holiday-新北市-中和店', 'holiday', '中和店', '新北市', '中和區', '新北市中和區景新街338號', true),
  ('holiday-新北市-土城店', 'holiday', '土城店', '新北市', '土城區', '新北市土城區中央路二段211號', true),
  ('holiday-新北市-樹林店', 'holiday', '樹林店', '新北市', '樹林區', '新北市樹林區鎮前街18號', true),
  ('holiday-新北市-三峽店', 'holiday', '三峽店', '新北市', '三峽區', '新北市三峽區文化路59號', true),
  ('holiday-桃園市-復興店', 'holiday', '復興店', '桃園市', '桃園區', '桃園市桃園區復興路70號', true),
  ('holiday-桃園市-桃中店', 'holiday', '桃中店', '桃園市', '桃園區', '桃園市桃園區中正路366號', true),
  ('holiday-桃園市-中美店', 'holiday', '中美店', '桃園市', '中壢區', '桃園市中壢區中美路二段137號', true),
  ('holiday-新竹市-新竹店', 'holiday', '新竹店', '新竹市', '東區', '新竹市東區中華路二段200號', true),
  ('holiday-苗栗縣-頭份店', 'holiday', '頭份店', '苗栗縣', '頭份市', '苗栗縣頭份市中正路169號', true),
  ('holiday-台中市-向陽店', 'holiday', '向陽店', '台中市', '豐原區', '台中市豐原區向陽路77號', true),
  ('holiday-台中市-西屯店', 'holiday', '西屯店', '台中市', '西屯區', '台中市西屯區河南路二段301巷60號', true),
  ('holiday-台中市-文心店', 'holiday', '文心店', '台中市', '北屯區', '台中市北屯區文心路四段821號', true),
  ('holiday-台中市-三民店', 'holiday', '三民店', '台中市', '北區', '台中市北區三民路三段136號', true),
  ('holiday-台中市-美村店', 'holiday', '美村店', '台中市', '西區', '台中市西區美村路一段272號', true),
  ('holiday-台中市-大里店', 'holiday', '大里店', '台中市', '大里區', '台中市大里區中興路二段446之5號', true),
  ('holiday-彰化縣-彰化店', 'holiday', '彰化店', '彰化縣', '彰化市', '彰化縣彰化市華山路22號', true),
  ('holiday-雲林縣-斗六店', 'holiday', '斗六店', '雲林縣', '斗六市', '雲林縣斗六市西平路20號', true),
  ('holiday-台南市-成功店', 'holiday', '成功店', '台南市', '中西區', '台南市中西區成功路99號', true),
  ('holiday-高雄市-楠梓店', 'holiday', '楠梓店', '高雄市', '楠梓區', '高雄市楠梓區瑞屏路1號', true),
  ('holiday-高雄市-中華店', 'holiday', '中華店', '高雄市', '前金區', '高雄市前金區中華三路11號', true),
  ('holiday-高雄市-建工店', 'holiday', '建工店', '高雄市', '三民區', '高雄市三民區建工路431號', true),
  ('holiday-屏東縣-東港店', 'holiday', '東港店', '屏東縣', '東港鎮', '屏東縣東港鎮中山路73號', true),
  ('holiday-宜蘭縣-宜蘭店', 'holiday', '宜蘭店', '宜蘭縣', '宜蘭市', '宜蘭縣宜蘭市舊城東路50號', true),
  ('holiday-宜蘭縣-羅東店', 'holiday', '羅東店', '宜蘭縣', '羅東鎮', '宜蘭縣羅東鎮公正路', true),
  ('holiday-花蓮縣-花蓮店', 'holiday', '花蓮店', '花蓮縣', '花蓮市', '花蓮縣花蓮市國聯五路69號', true),
  ('holiday-花蓮縣-玉里店', 'holiday', '玉里店', '花蓮縣', '玉里鎮', '花蓮縣玉里鎮中山路二段113號', true),
  ('holiday-台東縣-台東店', 'holiday', '台東店', '台東縣', '台東市', '台東縣台東市中華路一段572號', true),
  ('star-台北市-旗艦館', 'star', '旗艦館', '台北市', '大同區', '台北市大同區延平北路二段83號', true)
on conflict (id) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  city = excluded.city,
  district = excluded.district,
  address = excluded.address,
  enabled = excluded.enabled;
